### PR TITLE
hit formatting of diemodel input files

### PR DESCRIPTION
**Pull request by apb13**
## Reason

Update input files to align with current hit formatting standards in MOOSE.

## Design

Use script capabilities in MOOSE to update hit formatting. 

## Impact

Increased input file consistency and usability.

### CODE REVIEW

**Comment by apb13** [comment]
Performed comparison between the two csv files, one that was the original and another that received hit formatting, to ensure that the results were the same. Also ensured that comments were formatted correctly in the input file.
Refs https://github.com/idaholab/malamute/issues/128

**Comment by cticenhour** [comment]
@apb13 FYI - prior comments made by you can be edited (with version control!). So if you needed to edit the original post, as in this case, you can simply click on the "three dots" on the upper right of any GitHub comment and you'll get the following panel:
image

Then click on "Edit" to edit the post and click the "Update Comment" button to save! 

image

Just to be clear, you don't need to do this for this PR. I just wanted to share some GitHub tips and tricks for your future PRs!

**Comment by sapitts** [comment]
@cticenhour do you know what is going on with the Mac test for this PR by chance?

**Comment by cticenhour** [comment]
We only have a handful of "darwin-clang" (AKA Intel Mac) clients now that the Mac trashcans are no more, so it's likely just busy in the queue.

**Review by cticenhour — APPROVED** [review]

**Pull request merged**
