### PR TITLE
update SPS phase-field example input file for Y2O3 with Y-vacancies only

### LINKED ISSUE #77: Update SPS phase-field example input file for Y2O3 with Y-vacancies only
## Reason
Since the addition of the first example input file for phase-field simulation of SPS of Y2O3, further research has shown that the 2-particle geometry used in the initial input file does not adequately represent the physics of the process, even in a simplified way. 

## Design
Modify the example input file to reflect a 4-particle geometry and rename to make the name better reflect what is in the example.

## Impact
The input file is only tested with a `RunApp` test, so only the input file and its name in `tests` need to be changed.

### PR DESCRIPTION
**Pull request by laagesen**
Closes #77

### CODE REVIEW

**Comment by laagesen** [comment]
@cticenhour  the lone test failure seems unrelated to my PR, any idea what is happening with that?

**Comment by cticenhour** [comment]
I will pull your branch and see if I can duplicate locally. That test works fine on devel testing, to my knowledge.

**Comment by cticenhour** [comment]
I cannot get this to fail, so I think this might be a hiccup. I will invalidate.

**Comment by cticenhour** [comment]
@laagesen are you on an Intel machine or M1/M2? I don't have an Intel machine to test this on, so I'm working with @loganharbour on some way to duplicate this behavior.

**Comment by laagesen** [comment]
I am on Intel cheese grater Mac Pro. The test that is failing here didn't fail when I ran the tests in my Mac Pro prior to pushing and submitting the PR. The test has nothing to do with anything I modified, I only changed an unrelated input file, so I can't believe it's anything related to the PR

**Comment by cticenhour** [comment]
Yeah, definitely not arguing that. I'm just very puzzled as to why the test system decided to throw this error *now*. Thought it could be something our regular testing didn't catch in a submodule update, but our PR and level testing is reasonably well-aligned. Invalidating this to a cheesegrater test system rather than the older trashcans. I didn't get to complete my trashcan system testing before leaving yesterday.

**Review by cticenhour — APPROVED** [review]

**Comment by cticenhour** [comment]
Everything passed on a cheesegrater. Still going to check this against a trashcan machine on Monday, but I'm happy to merge.

**Pull request merged**
