### PR TITLE
Transition to MultiAppGeneralFieldNearestLocationTransfer

### LINKED ISSUE #100: Usage of MultiAppNearestNodeTransfer is deprecated
## Bug Description
`MultiAppNearestNodeTransfer` was deprecated as part of idaholab/moose#24196. It is used in the DED examples and is failing in scheduled deprecated testing (example: https://civet.inl.gov/job/1786984/)

## Steps to Reproduce
Run tests as of commit 1f1b349 and later with `--error-deprecated` enabled.

## Impact
Annoyance - no impact until `MultiAppNearestNodeTransfer` is removed.

### PR DESCRIPTION
**Pull request by cticenhour**
refs idaholab/moose#24196

closes #100

### CODE REVIEW

**Comment by jiangwen84** [comment]
@cticenhour is this just the name change? is any change to the original ```MultiAppNearestNodeTransfer```?  Since we did not TEST the results (only RunApp), I am not sure if the results change or not. Any thoughts?

**Review by jiangwen84 — APPROVED** [review]

**Comment by cticenhour** [comment]
This was a consolidation of the deprecated class into a more general one, though the behavior across MOOSE testing does not appear to change from before. I linked the MOOSE PR above if you want to take a look at the changes. Pinging @dewenyushu if she would like to run these cases to be very sure.

**Comment by cticenhour** [comment]
We've got quite some time to make this adjustment, so I am fine with waiting until we know the impact.

**Comment by jiangwen84** [comment]
I think we can merge it for now. If @dewenyushu finds any issue, we can revisit it later. Adding new golden files will be separate PR anyway.

**Pull request merged**
